### ISSUE TITLE
Cannot toggle chat window from outside Launcher

### ISSUE THREAD

**Issue by mmmikeal** [dharness/react-chat-window#29]
I'd like to be able to toggle the chat window by passing a function handler or some sort of prop to trigger Launcher's handleClick function. Perhaps bind Launcher's handle click in the constructor instead of render?

**Comment by mmmikeal** [comment]
im currently trying to implement this myself by copying the repo directly into my project and playing with Launcher

**Comment by dharness** [comment]
I agree this would be nice. I'll throw it on the backlog, and if you work something out, feel free to submit a PR. I'd prefer a prop `isOpen` or something. Is there a reason you want to hook directly into the `handleClick`?

**Comment by mmmikeal** [comment]
Yeah, I made a ghetto list of buttons to open up a specific chat from my current chats with different users. When I click that button I want the chat window for that user to toggle open. I finished it and will submit a pull request tomorrow after I clean up. I didn't use the handle click, just made a function that takes a boolean prop (into launcher) and sets the active state to true. It's really simple, but allows more flexibility in using your NPM module since I could only do it by actually going into launcher

**Comment by jacksonwildemurphy** [comment]
Hi, has this functionality been added? I'm using this component but have been unable to toggle the window open/closed programmatically. I see that @mmmikeal has submitted a pull request that was never emerged in, and a comment from @dharness in that request saying it was resolved in pull #34... 
Thanks for your work on this!

**Comment by dharness** [comment]
@jacksonwildemurphy It was resolved in https://github.com/dharness/react-chat-window/pull/34

but it never got republished to npm. Let me get to that shortly.

**Comment by mmmikeal** [comment]
i wrote my own solution, its pinned repo hokonodev/hokono on my github
profile

**Comment by jacksonwildemurphy** [comment]
@dharness , @mmmikeal  thank you both. I really appreciate it

**Comment by dharness** [comment]
This is complete and you can use it on https://github.com/dharness/react-chat-window/tree/rc-1.1.0

with the `isOpen` flag. It will also be part of the upcoming release.
