### ISSUE TITLE
Remove vestigial socket files

### ISSUE THREAD

**Issue by Nodonisko** [dharness/react-chat-window#36]
> There is no backend, and no communication system baked in.

What did file `services/messageBroker.js` do?

**Comment by dharness** [comment]
That's a good point @Nodonisko, that should not be in there.

The long and the short of it is that this component is an off-shoot of a larger project of mine called Slackchat which *does* provide a backend.

**Comment by dharness** [comment]
Closed by https://github.com/dharness/react-chat-window/pull/40
