### ISSUE TITLE
Reduxing

### ISSUE THREAD

**Issue by Bakhah** [dharness/react-chat-window#37]
Hi Dylan ! 
First, thank you for your work, I'm happy to have finally found a nice chat view ;)
I used it for a project, and I totally remelted it to be reduxed.
I also implemented Firebase to handle multiple conversations

Are you interested by a boilerplate version of it ?

Thank again and have a nice day !

**Comment by dharness** [comment]
Hey!

Great to hear. I'd love to see it -- can you share it here?

**Comment by Bakhah** [comment]
I will ! I need more time to find a good way to build the most generical implementation of Firebase (For the moment it's hardly bound to my business logic), but I can start with the reduxed version ;)

See you soon !

**Comment by dharness** [comment]
@Bakhah I'm going to close this due to lack of activity. If you still want to share, feel free to re-open!
