### ISSUE TITLE
Custom Styling

### ISSUE THREAD

**Issue by ishan28mkip** [dharness/react-chat-window#38]
Some other library was covering the whole page with z-index : 2, this should come above everything else hence I forced additional styling in the sc-launcher and sc-chat-window classes. It should probably support a custom styling option which would allow passing inline styles to the window as well as the launcher.

Also I wish to thank the author for creating such an awesome library and making it open source, the code is beautifully written and the library is well segmented, finally the flat design is just wonderful. I will definitely try to help you make it better whenever I get time.

**Comment by dharness** [comment]
Thanks Ishan, I appreciate the kind words. I think this has come up enough to spend some time thinking about how this would work. Let's add it as a feature request and we can work out the details here.

**Comment by dharness** [comment]
Upon further reflection I feel the best way forward is to continue to select individual elements directly in the host's css, and override their styles. You can have complete, transparent control in this way:

``` css
.my-wrapper .sc-message-list {
  background: red;
}
```
