### ISSUE TITLE
Make emjoi on toolbar optional

### ISSUE THREAD

**Issue by vkhattar** [dharness/react-chat-window#47]
The endpoint I use to send messages, does not allow emoji icons to be displayed. I do want the users to get confused when trying to use the emoji. Is there a way where we can have a settings and can maybe pass a props from launcher to hide/show the emoticon feature ? 
Thanks

**Comment by dharness** [comment]
I'll look at this. But in the interim, you can just set the emoji button to `display: none`

**Comment by mattmezza** [comment]
Has been implemented and merged in #64 

@dharness could you release a new version?

**Comment by dharness** [comment]
done.
