### ISSUE TITLE
Multiline chat message

### ISSUE THREAD

**Issue by TomYeoman** [dharness/react-chat-window#49]
Hi, great work I really like the chat window.

One issue I have is i'm unsure how to create a chat message which contains line breaks.

For example I have list data that looks like this

Data1 ) x
Data2 ) y
Data3 ) z

Is it possible to create newlines to break this data, rather than displaying all on one line?

Thanks :)

**Comment by dharness** [comment]
Definitely you should be able to have multi-line messages! Let's add this to the next release
