### ISSUE TITLE
Can't attach files

### ISSUE THREAD

**Issue by nnur** [dharness/react-chat-window#5]
it would be nice for ppl to be able to send pictures, pdfs, screenshots. especially if they need to get helped

**Comment by dharness** [comment]
I think this is also outside the scope of the project right now. But a nice to have later.

**Comment by dharness** [comment]
After thinking about this more here are the steps for this:

- [ ] add file upload icon
- [ ] fix styles of icon bar in chat window
- [ ] toggle file icon and send icon like intercom (when editing)
- [ ] allow the receipt of file messages in messageList
- [ ] display/preview/etc files displayed in the messageList
- [ ] allow the download of files from the messageList
