### ISSUE TITLE
Composer spacing is wrong on FF

### ISSUE THREAD

**Issue by dharness** [dharness/react-chat-window#54]
Spacing is weird on the bottom bar here:

<img width="380" alt="screen shot 2017-12-05 at 5 09 26 pm" src="https://user-images.githubusercontent.com/8755912/33639222-178dc7be-d9df-11e7-8b4d-7ac13ed1b21d.png">

Specifically on firefox. The spacing is too large.

**Comment by heatherbooker** [comment]
Closed in #81 .
