### ISSUE TITLE
Emoji picker is not aligned

### ISSUE THREAD

**Issue by dharness** [dharness/react-chat-window#56]
Emoji picker is not aligned, especially on FF:

<img width="365" alt="screen shot 2017-12-05 at 5 12 09 pm" src="https://user-images.githubusercontent.com/8755912/33639302-858aadd6-d9df-11e7-8f1f-be346bbc26d2.png">

It should be aligned, make sure to test on every browser

**Comment by xemasiv** [comment]
Great work on this man, solid!!!

**Comment by heatherbooker** [comment]
Closed in #81 .
