### ISSUE TITLE
ChatWindow error

### ISSUE THREAD

**Issue by cagigas** [dharness/react-chat-window#60]
I'm trying to use ChatWindow, as I'm only interested in the chatBox. I'm getting this error:

_Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. 

```
import {  ChatWindow  } from 'react-chat-window';

...
<ChatWindow
    messageList={this.state.messageList}
    onUserInputSubmit={this._onMessageWasSent.bind(this)}
    agentProfile={{
        teamName: this.props.user.firstname,
         imageUrl: this.props.user.profileImg.url
     }}
     isOpen={this.state.isOpen}
     onClose={this._handleClick.bind(this)}
/>

```
Do you see anything unusual?

**Comment by dharness** [comment]
Since it is the default export you need to remove the mustaches.

https://github.com/dharness/react-chat-window/blob/master/src/components/ChatWindow.js#L43

https://github.com/dharness/react-chat-window/blob/master/src/components/Launcher.js#L3

**Comment by cagigas** [comment]
`import ChatWindow from 'react-chat-window';
`
I'm still getting the same error.
