### ISSUE TITLE
connecting with dialogflow API.AI

### ISSUE THREAD

**Issue by bidyashish** [dharness/react-chat-window#63]
Hello,
I am unable to connect this app with my existing Jquery based dialogflow   CHATBOT ,

I   tried ti change messagelist . State ,
Please help me connect with API.AI

**Comment by dharness** [comment]
Hey @bidyashish these issues are for technical bugs and feature requests. If you want help with your project you can contact me through my consulting business at https://kingofthestack.com/at hello@kingofthestack.com

If you do find some problem with the library though, let me know here.
