### ISSUE TITLE
How can I add quick replies ?

### ISSUE THREAD

**Issue by Thomas-Negrault** [dharness/react-chat-window#66]
I would like to use quick replies in my chat (see [the messenger documentation](https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies))
It would basically be like a bubble, without the agent picture with some propositions, and when the user click on it, it is displayed as a user bubble.

Ideally, the quick replies could have a display value and an internal value (one displayed to the user, and one that can be sent to a backend API)

Do you plan to add this feature ? Or how can we set a custom component/message type in order to achieve this result ?

**Comment by dharness** [comment]
I don't have any plans to add this feature. I like the idea of adding custom message types, but don't have time to implement that right now.
