### ISSUE TITLE
Cant resolve css or assets v1.0.7

### ISSUE THREAD

**Issue by lightsinthesky** [dharness/react-chat-window#67]
It appears the project build is broken. Webpack 3.9.1, node v6.11.3, yarn 1.1.0. Digging deeper, none of the css or image assets are in the package.

**Comment by AhmedDaou** [comment]
I can confirm the same issue `react-chat-window": "^1.0.7"`

**Comment by dharness** [comment]
This should be resolved in `react-chat-window": "^1.0.8"`. We needed to add --copy-files to the build.
